websiteTitle: "ä¸ªäººä¸»é¡µ"
websiteFavicon: https://cdn.jsdelivr.net/gh/bot-bo/cdn@v1.0/images/background.png
beiAnNum:
avatar: https://cdn.jsdelivr.net/gh/bot-bo/cdn@v1.0/images/avatar.jpg
showWeather: 0


contacts:
  -
    id: 1
    icon: <svg t="1748057709425" class="icon" viewBox="0 0 1129 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="25723" width="200" height="200"><path d="M234.909 9.656a80.468 80.468 0 0 1 68.398 0 167.374 167.374 0 0 1 41.843 30.578l160.937 140.82h115.07l160.936-140.82a168.983 168.983 0 0 1 41.843-30.578A80.468 80.468 0 0 1 930.96 76.445a80.468 80.468 0 0 1-17.703 53.914 449.818 449.818 0 0 1-35.406 32.187 232.553 232.553 0 0 1-22.531 18.508h100.585a170.593 170.593 0 0 1 118.289 53.109 171.397 171.397 0 0 1 53.914 118.288v462.693a325.897 325.897 0 0 1-4.024 70.007 178.64 178.64 0 0 1-80.468 112.656 173.007 173.007 0 0 1-92.539 25.75h-738.7a341.186 341.186 0 0 1-72.421-4.024A177.835 177.835 0 0 1 28.91 939.065a172.202 172.202 0 0 1-27.36-92.539V388.662a360.498 360.498 0 0 1 0-66.789A177.03 177.03 0 0 1 162.487 178.64h105.414c-16.899-12.07-31.383-26.555-46.672-39.43a80.468 80.468 0 0 1-25.75-65.984 80.468 80.468 0 0 1 39.43-63.57M216.4 321.873a80.468 80.468 0 0 0-63.57 57.937 108.632 108.632 0 0 0 0 30.578v380.615a80.468 80.468 0 0 0 55.523 80.469 106.218 106.218 0 0 0 34.601 5.632h654.208a80.468 80.468 0 0 0 76.444-47.476 112.656 112.656 0 0 0 8.047-53.109v-354.06a135.187 135.187 0 0 0 0-38.625 80.468 80.468 0 0 0-52.304-54.719 129.554 129.554 0 0 0-49.89-7.242H254.22a268.764 268.764 0 0 0-37.82 0z m0 0" fill="#20B0E3" p-id="25724"></path><path d="M348.369 447.404a80.468 80.468 0 0 1 55.523 18.507 80.468 80.468 0 0 1 28.164 59.547v80.468a80.468 80.468 0 0 1-16.094 51.5 80.468 80.468 0 0 1-131.968-9.656 104.609 104.609 0 0 1-10.46-54.719v-80.468a80.468 80.468 0 0 1 70.007-67.593z m416.02 0a80.468 80.468 0 0 1 86.102 75.64v80.468a94.148 94.148 0 0 1-12.07 53.11 80.468 80.468 0 0 1-132.773 0 95.757 95.757 0 0 1-12.875-57.133V519.02a80.468 80.468 0 0 1 70.007-70.812z m0 0" fill="#20B0E3" p-id="25725"></path></svg>
    qrcode: /QQ-contact.jpg
    detail: å¯ä»¥æ‰«æä¸Šæ–¹äºŒç»´ç åŠ æˆ‘
    link: abc
  -
    id: 2
    icon: <svg t="1748057420697" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="8832" width="200" height="200"><path d="M689.6 347.7c11.7 0 23.2 0.9 34.6 2.1C693.1 206.5 538.2 100 361.5 100 163.9 99.9 2 233.2 2 402.5c0 97.7 53.9 177.9 143.9 240.1l-36 107 125.7-62.4c45 8.8 81.1 17.9 125.9 17.9 11.3 0 22.4-0.5 33.6-1.4C388 680 384 655 384 629.2c0-155.4 134.8-281.5 305.6-281.5z m-193.3-96.5c27.1 0 45 17.6 45 44.4 0 26.7-17.9 44.5-45 44.5-27 0-54-17.9-54-44.5 0.1-26.8 27.1-44.4 54-44.4z m-251.6 88.9c-27 0-54.2-17.9-54.2-44.5 0-26.8 27.2-44.4 54.2-44.4 26.9 0 44.9 17.6 44.9 44.4 0 26.7-17.9 44.5-44.9 44.5z" fill="#1BD66C" p-id="8833"></path><path d="M1022 630.3c0-142.2-143.8-258.2-305.4-258.2-171.1 0-305.8 115.9-305.8 258.2 0 142.4 134.7 258.1 305.8 258.1 35.8 0 71.9-8.9 107.8-17.8L923 924l-27-88.9c72.2-53.5 126-124.6 126-204.8z m-404.5-44.5c-17.9 0-36-17.6-36-35.6 0-17.7 18.1-35.6 36-35.6 27.2 0 45 17.8 45 35.6 0 18-17.8 35.6-45 35.6z m197.7 0c-17.8 0-35.7-17.6-35.7-35.6 0-17.7 17.9-35.6 35.7-35.6 27 0 45 17.8 45 35.6 0 18-18 35.6-45 35.6z" fill="#EFF3F9" p-id="8834"></path></svg>
    qrcode: /avator.jpg
    detail: å¯ä»¥æ‰«æä¸Šæ–¹äºŒç»´ç åŠ æˆ‘
    link: abc
  -
    id: 3
    icon: <svg t="1748057801444" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="26713" width="200" height="200"><path d="M656.90624 724.29056l47.42144-33.72544h52.68992V344.89856h-143.31904v346.7264h35.82976z" fill="#0066FF" p-id="26714"></path><path d="M849.92 51.2H174.08c-67.8656 0-122.88 55.0144-122.88 122.88v675.84c0 67.8656 55.0144 122.88 122.88 122.88h675.84c67.8656 0 122.88-55.0144 122.88-122.88V174.08c0-67.8656-55.0144-122.88-122.88-122.88zM495.66208 803.34848l-101.1712-157.05088 44.26752-31.616 67.45088 98.00704c-0.00512 0 23.17824 37.99552-10.5472 90.65984z m38.99392-276.10112v25.2928H408.19712C357.61152 876.06784 204.8 807.04512 204.8 807.04512c140.16512-109.86496 142.7968-254.50496 142.7968-254.50496H208.49152c0-57.9584 52.16256-56.91392 52.16256-56.91392h93.79328v-151.7568h-50.5856C284.89728 429.2352 204.8 425.02144 204.8 425.02144s32.67072-50.5856 54.79936-137.00096c22.12864-86.42048 89.5744-76.928 89.5744-76.928-20.0192 35.82976-29.50656 76.928-29.50656 76.928H485.12c40.04864 0 37.9392 25.2928 37.9392 25.2928v29.51168H411.35616v152.8064H503.04c33.72544 0 31.616 31.616 31.616 31.616zM819.2 747.49952h-102.22592l-88.51968 55.84896-8.42752-55.84896h-64.29184V288.01536H819.2v459.48416z" fill="#0066FF" p-id="26715"></path></svg>
    qrcode: /avator.jpg
    detail: å¯ä»¥æ‰«æä¸Šæ–¹äºŒç»´ç åŠ æˆ‘
    link: abc
  -
    id: 4
    icon:   <svg t="1748057866953" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="30006" width="200" height="200"><path d="M511.6 76.3C264.3 76.2 64 276.4 64 523.5 64 718.9 189.3 885 363.8 946c23.5 5.9 19.9-10.8 19.9-22.2v-77.5c-135.7 15.9-141.2-73.9-150.3-88.9C215 726 171.5 718 184.5 703c30.9-15.9 62.4 4 98.9 57.9 26.4 39.1 77.9 32.5 104 26 5.7-23.5 17.9-44.5 34.7-60.8-140.6-25.2-199.2-111-199.2-213 0-49.5 16.3-95 48.3-131.7-20.4-60.5 1.9-112.3 4.9-120 58.1-5.2 118.5 41.6 123.2 45.3 33-8.9 70.7-13.6 112.9-13.6 42.4 0 80.2 4.9 113.5 13.9 11.3-8.6 67.3-48.8 121.3-43.9 2.9 7.7 24.7 58.3 5.5 118 32.4 36.8 48.9 82.7 48.9 132.3 0 102.2-59 188.1-200 212.9 23.5 23.2 38.1 55.4 38.1 91v112.5c0.8 9 0 17.9 15 17.9 177.1-59.7 304.6-227 304.6-424.1 0-247.2-200.4-447.3-447.5-447.3z" p-id="30007"></path></svg>
    qrcode: /avator.jpg
    detail: å¯ä»¥æ‰«æä¸Šæ–¹äºŒç»´ç åŠ æˆ‘
    link: abc
  -
    id: 5
    icon: <svg t="1748057709425" class="icon" viewBox="0 0 1129 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="25723" width="200" height="200"><path d="M234.909 9.656a80.468 80.468 0 0 1 68.398 0 167.374 167.374 0 0 1 41.843 30.578l160.937 140.82h115.07l160.936-140.82a168.983 168.983 0 0 1 41.843-30.578A80.468 80.468 0 0 1 930.96 76.445a80.468 80.468 0 0 1-17.703 53.914 449.818 449.818 0 0 1-35.406 32.187 232.553 232.553 0 0 1-22.531 18.508h100.585a170.593 170.593 0 0 1 118.289 53.109 171.397 171.397 0 0 1 53.914 118.288v462.693a325.897 325.897 0 0 1-4.024 70.007 178.64 178.64 0 0 1-80.468 112.656 173.007 173.007 0 0 1-92.539 25.75h-738.7a341.186 341.186 0 0 1-72.421-4.024A177.835 177.835 0 0 1 28.91 939.065a172.202 172.202 0 0 1-27.36-92.539V388.662a360.498 360.498 0 0 1 0-66.789A177.03 177.03 0 0 1 162.487 178.64h105.414c-16.899-12.07-31.383-26.555-46.672-39.43a80.468 80.468 0 0 1-25.75-65.984 80.468 80.468 0 0 1 39.43-63.57M216.4 321.873a80.468 80.468 0 0 0-63.57 57.937 108.632 108.632 0 0 0 0 30.578v380.615a80.468 80.468 0 0 0 55.523 80.469 106.218 106.218 0 0 0 34.601 5.632h654.208a80.468 80.468 0 0 0 76.444-47.476 112.656 112.656 0 0 0 8.047-53.109v-354.06a135.187 135.187 0 0 0 0-38.625 80.468 80.468 0 0 0-52.304-54.719 129.554 129.554 0 0 0-49.89-7.242H254.22a268.764 268.764 0 0 0-37.82 0z m0 0" fill="#20B0E3" p-id="25724"></path><path d="M348.369 447.404a80.468 80.468 0 0 1 55.523 18.507 80.468 80.468 0 0 1 28.164 59.547v80.468a80.468 80.468 0 0 1-16.094 51.5 80.468 80.468 0 0 1-131.968-9.656 104.609 104.609 0 0 1-10.46-54.719v-80.468a80.468 80.468 0 0 1 70.007-67.593z m416.02 0a80.468 80.468 0 0 1 86.102 75.64v80.468a94.148 94.148 0 0 1-12.07 53.11 80.468 80.468 0 0 1-132.773 0 95.757 95.757 0 0 1-12.875-57.133V519.02a80.468 80.468 0 0 1 70.007-70.812z m0 0" fill="#20B0E3" p-id="25725"></path></svg>
    qrcode: /avator.jpg
    detail: å¯ä»¥æ‰«æä¸Šæ–¹äºŒç»´ç åŠ æˆ‘
    link: abc

selfTags:
  -
    title: æ¸¸æˆ
    data:
      -
        bgColor: '#2b2111'
        textColor: '#d89614'
        text: ç‹è€…è£è€€
        url: /index
      -
        bgColor: '#2b2111'
        textColor: '#d89614'
        text: å’Œå¹³ç²¾è‹±
  -
    title: çˆ±å¥½
    data:
      -
        bgColor: '#2b2111'
        textColor: '#d89614'
        text: æ‰“æ¸¸æˆ


tabs:
  test:
    name: é‡è¦é€šçŸ¥
    avail: true
    data : æ•°æ®æš‚æ—¶è¿˜æ²¡æœ‰å®Œå–„ï¼Œè¯·å°½æƒ…æœŸå¾…ğŸ˜‰


  friends:
    name: å‹æƒ…é“¾æ¥
    avail: true
    order : 1
    data:
      - title: ä»Šæ—¥å¤´æ¡
        link: https://lf9-static.bytednsdoc.com/obj/eden-cn/pipieh7nupabozups/toutiao_web_pc/icon_tt_192.png
        avatar: https://lf9-static.bytednsdoc.com/obj/eden-cn/pipieh7nupabozups/toutiao_web_pc/icon_tt_192.png
        desc: æ–°é—»ç½‘ç«™
        image: /avator.jpg
      - title: bilibili
        link: www.baidu.com
        avatar: https://ts4.tc.mm.bing.net/th/id/ODLS.1e67f861-d980-4c01-ba66-9450f90172f4
        desc: æˆ‘æ˜¯æè¿°
        image: /avator.jpg


skills:
  -
    icon: /material/java.png
    name: java
  -
    icon: /material/åƒé¥­.png
    name: åƒé¥­



websites:
  -
    iconUrl: /material/åšå®¢.png
    name: åšå®¢
    url: /index
    desc: ä¸ªäººåšå®¢


projects:
  -
    iconUrl: /avatar.jpg
    name: ä¸ªäººä¸»é¡µ
    url: https://www.baidu.com
    desc: å±•ç¤ºä¸ªäººä¿¡æ¯
  -
    iconUrl: /avator.jpg
    name: QQæœºå™¨äºº
    url: /index
    desc: èƒ½ä¸ç¾¤å‘˜äº’åŠ¨

#  -
#    iconUrl: /material/aiqiyi.png
#    name: çˆ±å¥‡è‰º
#    url: www.baidu.com
#    desc: ä¸€ä¸ªçœ‹ç”µå½±çš„ç½‘ç«™
#  -
#    iconUrl: /material/è…¾è®¯è§†é¢‘.png
#    name: è…¾è®¯è§†é¢‘
#    url: www.baidu.com
#    desc: ä¸€ä¸ªçœ‹ç”µå½±çš„ç½‘ç«™
#  -
#    iconUrl: /material/ç™¾åº¦.png
#    name: ç™¾åº¦
#    url: www.baidu.com
#    desc: ä¸€ä¸ªæœç´¢ç½‘ç«™
#  -
#    iconUrl: /material/ä¼˜é…·.png
#    name: ä¼˜é…·
#    url: www.baidu.com
#    desc: ä¸€ä¸ªçœ‹ç”µå½±çš„ç½‘ç«™
#  -
#    iconUrl: /material/è…¾è®¯ä¼šè®®.png
#    name: è…¾è®¯ä¼šè®®
#    url: www.baidu.com
#    desc: ä¸€ä¸ªåŠå…¬è½¯ä»¶
#  -
#    title: æˆ‘æ˜¯æ ‡é¢˜
#    link: www.baidu.com
#    avatar: www.baidu.com
#    desc: æˆ‘æ˜¯æè¿°
#    image: /avator.jpg






